# Generated by Django 4.1.3 on 2023-03-15 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hi',
        ),
    ]
