# Generated by Django 4.1.3 on 2023-03-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portspecification',
            name='lower',
            field=models.CharField(max_length=29),
        ),
        migrations.AlterField(
            model_name='portspecification',
            name='upper',
            field=models.CharField(max_length=29),
        ),
    ]
