# Generated by Django 5.0.6 on 2024-07-12 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='storage.gdpm_model'),
        ),
    ]
