# Generated by Django 4.1.3 on 2023-03-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_portspecification_lower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='lower',
            field=models.CharField(max_length=29),
        ),
        migrations.AlterField(
            model_name='support',
            name='upper',
            field=models.CharField(max_length=29),
        ),
    ]
