# Generated by Django 5.0.6 on 2024-07-12 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_job_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Constant',
        ),
        migrations.RemoveField(
            model_name='discrete',
            name='input',
        ),
        migrations.RemoveField(
            model_name='discrete',
            name='output',
        ),
        migrations.AddField(
            model_name='job',
            name='end_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Continuous',
        ),
        migrations.DeleteModel(
            name='PortSpecification',
        ),
        migrations.DeleteModel(
            name='Discrete',
        ),
        migrations.DeleteModel(
            name='Support',
        ),
    ]
