# Generated by Django 5.0.6 on 2024-07-14 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_delete_constant_remove_discrete_input_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gdpm_model',
            name='owner',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='gdpm_models', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
