# Generated by Django 5.0.6 on 2024-08-07 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_gdpm_model_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdpm_model',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gdpm_model',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=10),
        ),
    ]
