# Generated by Django 5.0.6 on 2024-10-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_gdpm_model_created_gdpm_model_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdpm_model',
            name='title',
            field=models.CharField(default='default_model'),
        ),
    ]
