# Generated by Django 5.0.6 on 2024-10-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_alter_gdpm_model_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdpm_model',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
