import Head from "next/head";
import Sidebar from "../components/sidebar";
import Workspace from "../components/workspace";

export default function Edit() {
  return (
    <>
      <Head>
        <title>GDPM - Edit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-full w-full">
        <Workspace className="h-full w-full" />
      </div>
    </>
  );
}
