export default [
  {
    distType: "operation",
    name: "+",
    displayName: "Addition",
    input: [
      {
        id: "left",
        name: "left",
        type: "float",
        upper: "inf",
        lower: "inf",
        upperInclusive: false,
        lowerInclusive: false,
        optional: false,
      },
      {
        id: "right",
        name: "right",
        type: "float",
        upper: "inf",
        lower: "inf",
        upperInclusive: false,
        lowerInclusive: false,
        optional: false,
      },
    ],
    output: {
      id: "support",
      type: "float",
      upper: "inf",
      lower: "-inf",
      upperInclusive: false,
      lowerInclusive: false,
    },
  },

  {
    distType: "operation",
    name: "-",
    displayName: "Subtraction",
    input: [
      {
        id: "left",
        name: "left",
        type: "float",
        upper: "inf",
        lower: "inf",
        upperInclusive: false,
        lowerInclusive: false,
        optional: false,
      },
      {
        id: "right",
        name: "right",
        type: "float",
        upper: "inf",
        lower: "inf",
        upperInclusive: false,
        lowerInclusive: false,
        optional: false,
      },
    ],
    output: {
      id: "support",
      type: "float",
      upper: "inf",
      lower: "-inf",
      upperInclusive: false,
      lowerInclusive: false,
    },
  },

  {
    distType: "operation",
    name: "*",
    displayName: "Multiplication",
    input: [
      {
        id: "left",
        name: "left",
        type: "float",
        upper: "inf",
        lower: "inf",
        upperInclusive: false,
        lowerInclusive: false,
        optional: false,
      },
      {
        id: "right",
        name: "right",
        type: "float",
        upper: "inf",
        lower: "inf",
        upperInclusive: false,
        lowerInclusive: false,
        optional: false,
      },
    ],
    output: {
      id: "support",
      type: "float",
      upper: "inf",
      lower: "-inf",
      upperInclusive: false,
      lowerInclusive: false,
    },
  },

  {
    distType: "operation",
    name: "/",
    displayName: "Division",
    input: [
      {
        id: "left",
        name: "left",
        type: "float",
        upper: "inf",
        lower: "inf",
        upperInclusive: false,
        lowerInclusive: false,
        optional: false,
      },
      {
        id: "right",
        name: "right",
        type: "float",
        upper: "inf",
        lower: "inf",
        upperInclusive: false,
        lowerInclusive: false,
        optional: false,
      },
    ],
    output: {
      id: "support",
      type: "float",
      upper: "inf",
      lower: "-inf",
      upperInclusive: false,
      lowerInclusive: false,
    },
  },
];
